Fix compatibility issues with Mac OS

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -1,6 +1,97 @@
 #!/usr/bin/env bash
 
-export ROOT_DIR=`dirname "$(readlink -f $0)"`
+# Minimum Bash version. Centos 7 Docker container comes with 4.2.46(2)-release,
+# and we will use that as the standard.
+MINIMAL_BASH_VERSION="4.2.0"
+
+# check_dependencies returns non-zero code when one or more dependencies are
+# not fulfilled
+check_dependencies() {
+    _check_bash_version
+    _check_coreutils
+    _check_grep
+}
+
+# _check_bash_version returns non-zero code when the bash version used is
+# too old
+_check_bash_version() {
+    local lowest_vesion=$(echo -e "$BASH_VERSION\n$MINIMAL_BASH_VERSION" | sort -V | head -n1)
+
+    if [ "$lowest_vesion" == "$BASH_VERSION" ]; then
+        echo "Installed Bash version is too old (installed=$BASH_VERSION," \
+            "required=$MINIMAL_BASH_VERSION)" >&2
+
+        if [ $(uname -s) == "Darwin" ]; then
+            echo "You can install newer Bash on Mac OS with:" >&2
+            echo "  $ brew install bash" >&2
+            echo "  $ sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'" >&2
+            echo "  $ chsh -s /usr/local/bin/bash " >&2
+        fi
+
+        return 1
+    fi
+}
+
+# _check_coreutils returns non-zero code if coreutils is not installed via APT
+# or brew
+_check_coreutils() {
+    local readlink_bin="readlink"
+
+    if [ $(uname -s) == "Darwin" ]; then
+        readlink_bin="greadlink"
+    fi
+
+    # If readlink or greadlink is not available, then coreutils is not installed
+    if ! which "$readlink_bin" > /dev/null; then
+        echo "System package \"coreutils\" is not installed." \
+            "You can install coreutils with:" >&2
+
+        if [ $(uname -s) == "Linux" ]; then
+            echo "  $ sudo apt-get install coreutils" >&2
+        elif [ $(uname -s) == "Darwin" ]; then
+            echo "  $ brew install coreutils" >&2
+        fi
+
+        return 1
+    fi
+}
+
+# _check_grep returns non-zero code if GNU grep is not installed via brew in
+# Mac OS
+_check_grep() {
+    if [ $(uname -s) != "Darwin" ]; then
+        return 0
+    fi
+
+    if ! which ggrep > /dev/null; then
+        echo "System package GNU grep is not installed." \
+            "You can install GNU grep with:" >&2
+        echo "  $ brew install grep" >&2
+
+        return 1
+    fi
+}
+
+if ! check_dependencies; then
+    echo "BCL dependencies not installed" >&2
+    exit 1
+fi
+
+# _readlink wraps readlink in Linux or greadlink in Mac OS. We need this here
+# since we can't import app/.helper/system yet.
+_readlink() {
+    if [ $(uname -s) == "Linux" ]; then
+        readlink "$@"
+        return $?
+    elif [ $(uname -s) == "Darwin" ]; then
+        greadlink "$@"
+        return $?
+    fi
+
+    echo "Invalid kernel name $(uname -s)" && return 1
+}
+
+export ROOT_DIR=`dirname "$(_readlink -f $0)"`
 CLI_ENTRYPOINT=`basename $0`
 
 . "$ROOT_DIR/utils"
diff --git a/complete b/complete
--- a/complete
+++ b/complete
@@ -1,9 +1,22 @@
 #!/usr/bin/env bash
 
+# _readlink wraps readlink in Linux or greadlink in Mac OS. We need this here
+# since we can't import app/.helper/system yet.
+_readlink() {
+    if [ $(uname -s) == "Linux" ]; then
+        readlink "$@"
+        return $?
+    elif [ $(uname -s) == "Darwin" ]; then
+        greadlink "$@"
+        return $?
+    fi
+
+    echo "Invalid kernel name $(uname -s)" && return 1
+}
 
 function _bash_cli() {
     local root_dir;
-    root_dir=`dirname "$(readlink -f "$(which ${COMP_WORDS[0]})")"`
+    root_dir=`dirname "$(_readlink -f "$(which ${COMP_WORDS[0]})")"`
 
     local curr_arg;
     curr_arg="${COMP_WORDS[COMP_CWORD]}"
diff --git a/framework/cli b/framework/cli
--- a/framework/cli
+++ b/framework/cli
@@ -1,6 +1,44 @@
 #!/usr/bin/env bash
 
-APP_DIR=`dirname "$(readlink -f $0)"`
+# kernel returns the kernel type of the system
+kernel() {
+    uname -s
+}
+
+# _readlink wraps readlink in Linux or greadlink in Mac OS
+_readlink() {
+    if [ $(kernel) == "Linux" ]; then
+        readlink "$@"
+        return $?
+    elif [ $(kernel) == "Darwin" ]; then
+        greadlink "$@"
+        return $?
+    fi
+
+    echo "readlink: invalid kernel name $(kernel)" >&2
+    return 1
+}
+
+# _grep wraps grep in Linux or ggrep in Mac OS
+_grep() {
+    if [ $(kernel) == "Linux" ]; then
+        grep "$@"
+        return $?
+    elif [ $(kernel) == "Darwin" ]; then
+        ggrep "$@"
+        return $?
+    fi
+
+    echo "grep: invalid kernel name $(kernel)" >&2
+    return 1
+}
+
+# Expose these functions to subshells and child processes
+export -f kernel
+export -f _readlink
+export -f _grep
+
+APP_DIR=`dirname "$(_readlink -f $0)"`
 PRJ_NAME="{{ project_name }}"
 APP_DIR="$APP_DIR/$PRJ_NAME"
 ROOT_DIR="$APP_DIR/framework"
diff --git a/framework/complete b/framework/complete
--- a/framework/complete
+++ b/framework/complete
@@ -1,10 +1,22 @@
 #!/usr/bin/env bash
 
+# _readlink wraps readlink in Linux or greadlink in Mac OS.
+_readlink() {
+    if [ $(uname -s) == "Linux" ]; then
+        readlink "$@"
+        return $?
+    elif [ $(uname -s) == "Darwin" ]; then
+        greadlink "$@"
+        return $?
+    fi
+
+    echo "Invalid kernel name $(uname -s)" && return 1
+}
 
 function {{ function_name }}() {
     local root_dir;
     local project_name={{ project_name }};
-    root_dir=`dirname "$(readlink -f "$(which ${COMP_WORDS[0]})")"`
+    root_dir=`dirname "$(_readlink -f "$(which ${COMP_WORDS[0]})")"`
     root_dir="$root_dir/$project_name"
 
     # If the project directory is not found, then the command might be called as
